version: '3.8'

services:
  spring-app:
    image: maven:3.8.8-eclipse-temurin-17
    container_name: todo-app-spring-boot
    volumes:
      - .:/app
    working_dir: /app
    command: mvn clean spring-boot:run
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd@123
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SERVER_PORT: 8081
      SERVER_SERVLET_CONTEXT_PATH: /api/v1/todo
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd@123
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
